# Generated by Django 5.2.6 on 2025-09-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PopularCity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("name_nepali", models.CharField(blank=True, max_length=100)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("province", models.CharField(max_length=100)),
                ("search_count", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Popular Cities",
                "ordering": ["-search_count", "name"],
            },
        ),
        migrations.CreateModel(
            name="WeatherSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("search_time", models.DateTimeField(auto_now_add=True)),
                ("success", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-search_time"],
            },
        ),
        migrations.CreateModel(
            name="WeatherData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("country", models.CharField(default="NP", max_length=10)),
                ("temperature", models.FloatField()),
                ("feels_like", models.FloatField()),
                ("humidity", models.IntegerField()),
                ("pressure", models.IntegerField()),
                ("description", models.CharField(max_length=200)),
                ("icon_code", models.CharField(max_length=10)),
                ("wind_speed", models.FloatField()),
                ("visibility", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
                "unique_together": {("city", "country")},
            },
        ),
    ]
